apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
  - name: mysql-client
    image: mysql:8.0
    command: ["sleep", "3600"]
    env:
    - name: MYSQL_HOST
      valueFrom:
        configMapKeyRef:
          name: mysql-client-config
          key: MYSQL_HOST
    - name: MYSQL_USER
      valueFrom:
        configMapKeyRef:
          name: mysql-client-config
          key: MYSQL_USER
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-root-password
          key: MYSQL_ROOT_PASSWORD
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
